spring:
  application:
    name: ecom-application

  datasource:
    url: jdbc:postgresql://localhost:5432/ecom_db
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect # to make sure queries are generated properly

#  datasource:
#    url: jdbc:mysql://localhost:3306/ecom_db
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}

#  datasource:
#    url: jdbc:h2:mem:ecom_db
#    driverClassName: org.h2.Driver
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

#  jpa:
#    hibernate:
#      ddl-auto: create # when use "create" jpa delete existing tables then create new tables
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
#    shutdown:
#      enabled: true


  info:
    env:
      enabled: true

info:
  app:
    name: MyNewApp
    description: App built by us
    version: 1.0.3


